### ISSUE TITLE
Breaking Change Script

### ISSUE THREAD

**Issue by SolarWindss** [SolarWindss/Hearthstone.js#54]
**Is your feature request related to a problem? Please describe.**
When making a breaking change, you need to fix the cards. However you don't know which cards are affected by the breaking change, so you need to go through every single card, check if it is using the thing you changed, if it does: fix it, if it doesn't: move on to the next card.

**Describe the solution you'd like**
Make a script where you can type in a word to search for. It will then search the cards for that word, and tell you which cards use it. You can then open it in your favorite text editor and fix it. Once it's fixed, you can mark it as done in the script and move on to the next one. Remember which one is fixed by saving it to a file, that only gets deleted when all instances are fixed.

**Describe alternatives you've considered**
None

**Additional context**
This will make breaking changes a lot easier to do, but ideally, there wouldn't be any breaking changes.  This is why #19 is so important.

**Comment by SolarWindss** [comment]
Todo:
Add issue for renaming the card generator to the vanilla card creator
Add issue for support for vanilla deckcodes.

**Comment by LunarTides** [comment]
I realise that i just reinvented searching in an ide, so this was removed just prior to 2.0
